Enhancements to Java config
DualSpark/superlumic-basic pull request #9
Opened 2016-10-07 15:14 UTC by liebowitz

- Copy default maven global settings

2016-10-07 18:16 UTC, chrislovecnm requested changes
Just a question about URLs

2016-10-07 18:16 UTC, chrislovecnm commented on files/maven_settings.xml
> +      <url>https://artifactory.automate.datapipe.net:443/remote-repos</url>
Any way to not put in backend url?

2016-10-07 19:03 UTC, liebowitz commented on files/maven_settings.xml
> +      <url>https://artifactory.automate.datapipe.net:443/remote-repos</url>
I'd prefer to externalize it as well, but I don't believe it is possible in this case...

2016-10-09 21:32 UTC, chrislovecnm commented on files/maven_settings.xml
> +      <url>https://artifactory.automate.datapipe.net:443/remote-repos</url>
ENV vars?

2016-10-13 15:01 UTC, liebowitz commented
Closing and moving config to platform parent POM.

2016-10-13 15:01 UTC, closed without merging